[package]
name = "rust-usage"
version = "0.1.0"
authors = ["Elias.Yao <siran0611@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.53"
thiserror = "1.0.30"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html