[package]
name = "v8-live"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.41.0"
serde_v8 = "0.37"
serde = "1.0.136"
serde_json = "1.0.42"